version: '3.4'

services:
  shopping.api:
    container_name: shoppingapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb+srv://is402:Baitap7!@is402.mongocluster.cosmos.azure.com/?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000"
    depends_on:
      - shopping.db
    ports:
      - "8000:80"

  shopping.client:
    container_name: shoppingclient
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ShoppingAPIUrl=http://shoppingapi"
    depends_on:
          - shopping.db
          - shopping.api
    ports:
      - "8001:80"
 
  shopping.db:
    container_name: shoppingdb
    restart: always
    ports:
        - "27017:27017"
    volumes: 
      - ${WEBAPP_STORAGE_HOME}/site:/data/db

